// AUTO-GENERATED by scripts/sync-shared.mjs — do not edit.
// Run `pnpm sync:shared` after changing shared-references/ or a skill's references.

export const SURFACES = ["blog","linkedin","newsletter","release-notes","x"] as const;

export type Surface = (typeof SURFACES)[number];
